config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons do
    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy], param: :question_id, :constraints => OnlyAjaxRequest do
      member do
        get '/answers' => 'answers#index', :constraints => OnlyAjaxRequest
      end
    end
    resources :students, only: [] do
      scope '/questions/:question_id' do
        resources :answers, only: [:index]
      end
    end
    collection do
      get '/join' => 'user_lessons#new'
      post '/join' => 'user_lessons#create'
      get ':lesson_id/students' => 'lessons#students', as: 'students', :constraints => OnlyAjaxRequest
      get ':lesson_id/students/:student_id' => 'lessons#student', as: 'student', :constraints => OnlyAjaxRequest
    end
  end

  scope :ajax do
    get 'answers/select_version' => 'answers#select_version'
    get 'lessons/tab_back_home' => 'lessons#tab_back_home'
    post 'answers/diff_select' => 'answers#diff_select'
    post 'lessons/internet_check' =>'lessons#internet_check'
    post 'questions/get_exist_question' => 'questions#get_exist_question'
  end

  get '/public_questions' => 'questions#public_questions', :as => 'questions'
  resources :questions, only: [:show], param: :question_id do
    member do
      get '/answers' => 'answers#index'
    end
  end
  resources :answers, only: [:create]

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  scope :help, :as => :help do
    get '/' => 'help#index'
    get '/index' => 'help#index'
    get '/user_create' => 'help#user_create'

    get '/student_attend_lesson' => 'help#student_attend_lesson'
    get '/student_view_question' => 'help#student_view_question'
    get '/student_answer' => 'help#student_answer'
    get '/student_result' => 'help#student_result'

    get 'teacher_lesson_create' => 'help#teacher_lesson_create'
    get 'teacher_question_create' => 'help#teacher_question_create'
    get 'teacher_view_answer' => 'help#teacher_view_answer'
    get 'teacher_view_result' => 'help#teacher_view_result'
    get 'teacher_web_plagiarism' => 'help#teacher_web_plagiarism'
    get 'teacher_local_plagiarism' => 'help#teacher_local_plagiarism'

    get 'admin_admin_page' => 'help#admin_admin_page'
    get 'admin_user_roles' => 'help#admin_user_roles'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/question.rb
# -*- coding: utf-8 -*-
class Question < ActiveRecord::Base
  has_many :lesson_questions, :foreign_key => :question_id, :inverse_of => :question
  has_many :lessons, :through => :lesson_questions

  has_many :samples, :foreign_key => :question_id, :inverse_of => :question
  has_many :test_data, :foreign_key => :question_id, :inverse_of => :question
  has_many :answers, :foreign_key => :question_id
  has_many :question_keywords, :foreign_key => :question_id, :inverse_of => :question

  belongs_to :user, :foreign_key => :author

  accepts_nested_attributes_for :samples, allow_destroy: false, reject_if: :all_blank
  accepts_nested_attributes_for :test_data, allow_destroy: false, reject_if: :all_blank
  accepts_nested_attributes_for :lesson_questions, allow_destroy: false, reject_if: :all_blank
  accepts_nested_attributes_for :question_keywords, allow_destroy: false, reject_if: :all_blank

  validates :title, :presence => true
  validates :content, :presence => true
  validates :run_time_limit, :presence => true
  validates_numericality_of :run_time_limit, less_than: CPU_TIME_LIMIT
  validates :memory_usage_limit, :presence => true
  validates_numericality_of :memory_usage_limit, less_than: MEMORY_LIMIT
  validates :author, :presence => true


  rails_admin do
    weight 3

    create do
      field :title do
        required true
      end
      field :content do
        required true
        help "問題の説明など, #{help}"
      end
      field :input_description
      field :output_description
      field :run_time_limit do
        required true
        help "単位はms, #{help}"
      end
      field :memory_usage_limit do
        required true
        help "単位はMB, #{help}"
      end
      field :author, :enum do
        required true
        enum do
          User.all.collect { |u| ["#{u.nickname}", u.id] }
        end
      end

      field :lessons
      field :version do
        required true
        help "問題を編集した場合に更新される値, #{help}"
      end
      field :is_public do
        help "この問題をパブリック問題として公開するかどうか, 非公開への変更は管理画面からのみ可能#{help}"
      end
    end

    edit do
      field :title do
        required true
      end
      field :content do
        required true
        help "問題の説明など, #{help}"
      end
      field :input_description
      field :output_description
      field :run_time_limit do
        required true
        help "単位はms, #{help}"
      end
      field :memory_usage_limit do
        required true
        help "単位はMB, #{help}"
      end
      field :author do
        required true
      end
      field :lessons
      field :version do
        required true
        help "問題を編集した場合に更新される値, #{help}"
      end
      field :is_public do
        help "この問題をパブリック問題として公開するかどうか, 非公開への変更は管理画面からのみ可能#{help}"
      end
    end

    list do
      field :id
      field :title
      field :content
      field :lessons
      field :input_description
      field :output_description
      field :run_time_limit
      field :memory_usage_limit
      field :version
      field :user
      field :is_public
      field :samples
      field :test_data
      field :created_at
      field :updated_at
    end

    show do
      exclude_fields :lesson_questions
    end
  end

end

app/controllers/questions_controller.rb
# -*- coding: utf-8 -*-
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_question, only: [:show]
  before_action :check_lesson, only: [:index, :new]


  # get '/lessons/:lesson_id/questions'
  # 問題一覧を表示
  # @param [Fixnum] lesson_id
  def index
    lesson_id = params[:lesson_id] || session[:lessson_id] || 1
    session[:lesson_id] = lesson_id
    @lesson = Lesson.find_by(:id => lesson_id)
    @is_teacher = @lesson.user_lessons.find_by(:user_id => current_user.id).is_teacher
    @questions = @lesson.lesson_questions
  end

  # get '/questions'
  # 問題一覧を表示
  def public_questions
    lesson_id = 1
    session[:lesson_id] = lesson_id
    session[:lesson_question_id] = 1
    @lesson = Lesson.find_by(:id => lesson_id)
    @questions = @lesson.lesson_questions
    render 'index'
  end

  def new
    @question = Question.new
    @question_id = Question.count
    @question.samples.build
    @question.test_data.build
    @question.lesson_questions.build
    @question.question_keywords.build
    @lesson_id = params[:lesson_id].to_i || session[:lesson_id]
    my_questions = (Question.where(:is_public => true) + Question.where(:author => current_user.id, :is_deleted => false)).uniq.sort
    @exist_question = my_questions.map{|q| [q.title, q.id]}.to_h
  end

  def create
    lesson_id = params[:lesson_id] || session[:lesson_id]
    question_id = params[:question_id] || session[:question_id]

    ##ファイルサイズは10MB以上の場合　#ajax
    # 保存失敗時のajax用の変数
    params[:lesson_id] = lesson_id
    @lesson = Lesson.find_by(:id => lesson_id)
    @questions = @lesson.lesson_questions
    @is_teacher = @lesson.user_lessons.find_by(:user_id => current_user.id, :lesson_id => lesson_id).is_teacher

    if flash[:is_refer]
      lesson_question = LessonQuestion.new(:question_id => question_id,
                                           :lesson_id => lesson_id,
                                           :start_time => params[:start_time],
                                           :end_time => params[:end_time])
      if lesson_question.save
        flash.now[:notice] = '問題を登録しました'
      else
        flash.now[:notice] = '問題を登録に失敗しました'
      end
      return
    end

    # アップロードされたテストデータを取得
    # TestDatumモデルにはファイル名を入力
    test_data = {}
    params[:question][:test_data_attributes].each.with_index(1) do |(key, val), i|
      files = {}

      # データが無い項目は無視
      if val[:input].nil?
        next
      end

      # ファイルの取得
      files[:input] = val[:input]
      files[:output] = val[:output]
      if files[:input].size > 10.megabyte || files[:output].size > 10.megabyte
        flash.now[:alert] = 'ファイルサイズは10MBまでにしてください。'
        return
      end

      # ファイルの入っていた項目にファイル名などを保存
      val[:input] = val[:input].original_filename
      val[:output] = val[:output].original_filename
      val[:input_storename] = "input#{i}"
      val[:output_storename] = "output#{i}"
      test_data["#{i}"] = files
    end
    params[:question][:version] = 1

    # パブリック化の有無
    if params[:question][:is_public] != "false"
      params[:question][:lesson_questions_attributes]['100101010'] = {'lesson_id' => "1"}
    end

    @question = Question.new(question_params)
    @question.author = current_user.id


    if @question.save
      flash.now[:notice] ='問題を登録しました'

      # テストデータのディレクトリを作成
      uploads_test_data_path = UPLOADS_QUESTIONS_PATH.join(@question.id.to_s)
      FileUtils.mkdir_p(uploads_test_data_path) unless FileTest.exist?(uploads_test_data_path)

      # テストデータの保存
      test_data.each do |key, val|
        File.open("#{uploads_test_data_path}/input#{key}", "wb") do |f|
          f.write(val[:input].read)
        end
        File.open("#{uploads_test_data_path}/output#{key}", "wb") do |f|
          f.write(val[:output].read)
        end
      end

      flash.now[:notice]  = '問題を登録しました'

    else
      flash.now[:notice] ='問題の登録に失敗しました'
    end
  end

  # get '/lessons/:lesson_id/questions/:question_id'
  # 問題詳細を表示
  # @param [Fixnum] lesson_id
  # @param [Fixnum] id Questionのid
  # @param [Fixnum] lesson_question_id
  def show
    session[:lesson_question_id] = params[:lesson_question_id].present? ? params[:lesson_question_id] : session[:lesson_question_id]
    session[:question_id] = params[:question_id]
    lesson_question_id = session[:lesson_question_id]
    question_id = session[:question_id] || LessonQuestion.find_by(:id => session[:lesson_question_id]).question_id
    lesson_id = session[:lesson_id] || 1
    unless check_lesson_question(:lesson_id => lesson_id,
                                 :question_id => question_id,
                                 :lesson_question_id => lesson_question_id)
      return
    end

    @question = Question.find_by(:id => question_id)
    @lesson = Lesson.find_by(:id => lesson_id)
    @latest_answer = Answer.latest_answer(:student_id => current_user.id,
                                          :question_id => question_id,
                                          :lesson_id => lesson_id,
                                          :lesson_question_id => lesson_question_id) || nil

    @is_teacher = UserLesson.find_by(:user_id => current_user.id, :lesson_id => lesson_id).is_teacher
    if @is_teacher
      @plagiarism_have_keyword = 0
      @multi_check_todo = 0     #0の場合、既に検索完了
      @key_word_change = 0        # 1の場合、キーワードの変更があり、 再検索を行う
      @have_accepted_answer = 0   #1の場合、全員チェックボタンを有効になる
      @question_keyword =''

      question_keywords = QuestionKeyword.where(:question_id => @question['id'])
      question_keywords.each do |k|
        @plagiarism_have_keyword = 1
        @question_keyword = @question_keyword + " " + k['keyword']
      end
      @students = User.where(:id => @lesson.user_lessons.where(:is_teacher => false).pluck(:user_id))
      @students.each do |s|
        answer = Answer.latest_answer(:student_id => s.id, :question_id => @question.id, :lesson_id => @lesson.id, :lesson_question_id => lesson_question_id)

        if answer.present?
          if answer['result'] == 'A'
            @have_accepted_answer = 1
          end
          checked_result = InternetCheckResult.where(:answer_id =>answer.id)
          if checked_result.count == 0
            @multi_check_todo = 1
          else
            checked_result.each do |r|
              if r['key_word']!= @question_keyword
                @key_word_change = 1
              end
              if r['title']==nil && r['link']=='' && r['content']==''
                @multi_check_todo = 1
              end
            end
          end
        end
        if @multi_check_enable == true && @have_submit_answer == true
          break
        end
      end
    else
      @languages = LANGUAGES.map { |val| [val, val.downcase] }.to_h
    end


  end

  def edit
    @lesson_id = params[:lesson_id]
    @question_id = params[:question_id]
    @question = Question.find_by(:id =>@question_id)
    @is_public = @question.is_public
  end

  def update
    @lesson_id = params[:lesson_id] || session[:lesson_id]
    @question_id = params[:question_id] || session[:question_id]
    @question = Question.find_by(:id =>@question_id)

    ##ajax
    params[:lesson_id] = @lesson_id
    @lesson = Lesson.find_by(:id => @lesson_id)
    @questions = @lesson.lesson_questions
    @is_teacher = Lesson.find_by(:id => @lesson_id).user_lessons.find_by(:user_id => current_user.id, :lesson_id => @lesson_id).is_teacher

    version_up = false
    test_data = {}
    start_num = @question.test_data.size

    if @question.run_time_limit != params[:question][:run_time_limit].to_i || @question.memory_usage_limit != params[:question][:memory_usage_limit].to_i
      version_up = true
    end

    params[:question][:samples_attributes].each do |key, val|
      if val[:_destroy] != 'false'
        val[:is_deleted] = true
      end
    end

    if params[:question][:question_keywords_attributes]
      params[:question][:question_keywords_attributes].each do |key, val|
        if val[:_destroy] != 'false'
          val[:is_deleted] = true
        end
      end
    end

    params[:question][:test_data_attributes].each.with_index(1) do |(key, val), i|
      if val[:input].nil? || val[:output].nil?
        next
      end

      files = {}
      if val["id"].to_s == ""
        version_up = true
        files[:input] = val[:input]
        files[:output] = val[:output]
        if files[:input].size > 10.megabyte || files[:output].size > 10.megabyte
          flash.now[:alert] = 'ファイルサイズは10MBまでにしてください。'
          return
        end
        start_num = start_num + 1

        val[:input] = val[:input].original_filename
        val[:output] = val[:output].original_filename
        val[:input_storename] = "input#{start_num}"
        val[:output_storename] = "output#{start_num}"
        test_data["#{start_num}"] = files
      end

      if val[:_destroy] != 'false'
        version_up = true
        val[:is_deleted] = true
      end
   end

    if version_up
      params[:question][:version] = params[:question][:version].to_i + 1
    end

    # パブリック化の有無
    if (params[:question][:is_public] != "false") && (@question.is_public != true)
      params[:question][:lesson_questions_attributes]['100101010'] = {'lesson_id' => "1"}
    end

    if @question.update(params[:question])

      # テストデータのディレクトリを作成
      uploads_test_data_path = UPLOADS_QUESTIONS_PATH.join(@question.id.to_s)
      FileUtils.mkdir_p(uploads_test_data_path) unless FileTest.exist?(uploads_test_data_path)

      # テストデータの保存
      test_data.each do |key, val|
        File.open("#{uploads_test_data_path}/input#{key}", "wb") do |f|
          f.write(val[:input].read)
        end
        File.open("#{uploads_test_data_path}/output#{key}", "wb") do |f|
          f.write(val[:output].read)
        end
      end
      flash.now[:notice]  = '問題を更新しました'
    else
      flash.now[:notice] ='問題の更新に失敗しました'
    end

  end

  def get_exist_question
    question_id = params[:question_id]

app/helpers/questions_helper.rb
module QuestionsHelper
  def show_local(filepath)
    code = File.open(filepath, 'r:utf-8')
    return code
  end
end

app/views/questions/_index.html.erb
<%= render "layouts/notice" %>
<div class="btn-right">
  <% if @is_teacher && session[:seleted_lesson] != "private_lesson"  %>
    <%= link_to "問題新規作成",new_lesson_question_path(:lesson_id => @lesson.id) ,:remote => true ,:class=>"btn btn-primary" %>
  <% end %>
</div>
<div>

  <h2>問題一覧</h2>
  <div class="table-responsive">
    <% unless @is_teacher %>
      <div>
        <div style="float:right;"><p>問題変更前の回答です</p></div>
        <div style="float:right;"><div class="old_version_color_block"></div></div>
      </div>
    <% end %>
    <table class="table table-bordered table-striped">
      <tr>
        <th>問題ID</th>
        <th>問題名</th>
        <% if @lesson.id != 1 %>
          <th>開始時間</th>
          <th>終了時間</th>
        <% end %>
        <% unless @is_teacher %>
          <th>結果</th>
          <th>解答</th>
          <th>解答詳細</th>
        <% end %>
      </tr>
      <% i = 0 %>
      <% @questions.each do |lesson_question| %>

        <% if lesson_question.is_deleted == true%>
          <% next %>
        <% end %>
        <% i += 1 %>
        <% question = Question.find_by(:id => lesson_question.question_id) %>
        <tr>
          <td><%= i %></td>
          <td>
            <% if @lesson.id != 1 %>
              <%= link_to(question.title, lesson_question_path(:lesson_id => params[:lesson_id],
                                                               :question_id => question.id,
                                                               :lesson_question_id => lesson_question.id),:remote =>true) %>
            <% else %>
              <%= link_to(question.title, question_path(:question_id => question.id,:lesson_question_id => lesson_question.id)) %>
            <% end %>
          </td>

          <% if @lesson.id != 1 %>
            <td>
              <% if lesson_question.start_time.nil? %>
                <%= lesson_question.start_time %>
              <% else %>
                <%= lesson_question.start_time.strftime(" %Y /  %m / %d - %H:%M:%S ")  %>
              <% end %>
            </td>
            <td>
              <% if lesson_question.end_time.nil? %>
                <%= lesson_question.end_time %>
              <% else %>
                <%= lesson_question.end_time.strftime(" %Y /  %m / %d - %H:%M:%S ") %>
              <% end %>
            </td>
          <% end %>

          <% unless @is_teacher %>
            <% @latest_answer = Answer.latest_answer(:student_id => current_user.id,
                                                     :question_id => question.id,
                                                     :lesson_id => @lesson.id,
                                                     :lesson_question_id => lesson_question.id) || Answer.new %>

            <% if question.version == @latest_answer.question_version %>
              <td><%= RESULT[@latest_answer.result] %></td>
            <% else %>
              <% if RESULT[@latest_answer.result].to_s.empty?%>
                <td ><%= RESULT[@latest_answer.result] %></td>
              <% else %>
                <td class = "old_version_color"><%= RESULT[@latest_answer.result] %></td>
              <% end %>
            <% end %>
            <td>
              <% if @lesson.id != 1 %>
                <!--現在時間と開始時間・終了時間を比較し、時間内かどうかを確認する-->
                <% if (lesson_question.start_time.nil? || lesson_question.start_time.to_time < Time.now) &&
                       (lesson_question.end_time.nil? || Time.now < lesson_question.end_time.to_time) %>
                <%= button_to('解答', lesson_question_path(:lesson_id => params[:lesson_id],
                                                           :question_id => question.id,
                                                           :lesson_question_id => lesson_question.id) + '#answer',
                              :method => :get, :remote => true, class: 'btn btn-default') %>
                <% else %>
                  <%= button_to('解答', lesson_question_path(:lesson_id => params[:lesson_id],
                                                             :question_id => question.id,
                                                             :lesson_question_id => lesson_question.id),
                                :method => :get, :disabled => true, :remote => true, class: 'btn btn-default') %>
                <% end %>
              <% else %>
                <%= button_to('解答', question_path(:question_id => question.id) + '#answer',
                              :method => :get, class: 'btn btn-default',
                              :params => {:lesson_question_id => lesson_question.id}) %>
              <% end %>
            </td>
            <td>
              <% if @lesson.id != 1 %>
                <%= button_to('解答詳細', answers_lesson_question_path(:lesson_id => @lesson.id,
                                                                       :question_id => question.id,
                                                                       :lesson_question_id => lesson_question.id),
                              :method => :get, :disabled => (@latest_answer.new_record?), :remote => true, class: 'btn btn-default') %>
              <% else %>
                <%= button_to('解答詳細', answers_question_path(:question_id => question.id),
                              :method => :get, :disabled => (@latest_answer.new_record?), class: 'btn btn-default',
                              :params => {:lesson_question_id => lesson_question.id}) %>
              <% end %>

            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <% if @is_teacher && @lesson.id != 1 %>
    <% private_question_show = false %>
    <% all_delete_question = LessonQuestion.where(:lesson_id => @lesson.id,:is_deleted =>true) %>
    <% all_delete_question.each do |d| %>
      <% q = Question.find(d.question_id) %>
      <% if q.is_public == true %>
        <% private_question_show =true %>
        <% break %>
      <% end %>
      <% answers = Answer.where(:lesson_id=>@lesson.id, :question_id =>d.question_id, :lesson_question_id => d.id)%>
      <% if answers.count > 0 %>
          <% private_question_show = true %>
          <% break %>
      <% end %>
    <% end %>
    <% if  private_question_show == true %>
      <h2><font color="red">非公開問題一覧</font></h2>
      <p>非公開問題は学生に表示されません．再公開したい場合はシステム管理者に連絡してください.</p>
      <p>問題再利用したい場合は問題を参照して作成できます.</p>
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tr>
            <th>問題ID</th>
            <th>問題名</th>
            <th>開始時間</th>
            <th>終了時間</th>
          </tr>
          <% ii = 0 %>
          <% @questions.each do |question_lesson| %>
              <tr>
                <% question_private = Question.find_by(:id => question_lesson.question_id) %>
                <% answers = Answer.where(:lesson_id=>@lesson.id, :question_id =>question_lesson.question_id, :lesson_question_id => question_lesson.id)%>
                <% if (question_lesson.is_deleted == true && question_private.is_public == true ) || (question_lesson.is_deleted == true && answers.count>0 )%>
                    <% ii += 1 %>

                    <td><%= ii  %></td>
                    <td>
                      <%= link_to(question_private.title, lesson_question_path(:lesson_id => params[:lesson_id], :question_id => question_private.id, :lesson_question_id => question_lesson.id),:remote =>true) %>
                    </td>
                    <td>
                      <% if @lesson.lesson_questions.find_by(:id => question_lesson.id).start_time.nil? %>
                          <%= @lesson.lesson_questions.find_by(:id => question_lesson.id).start_time %>
                      <% else %>
                          <%= @lesson.lesson_questions.find_by(:id => question_lesson.id).start_time.strftime(" %Y /  %m / %d - %H:%M:%S ")  %>
                      <% end %>
                    </td>
                    <td>
                      <% if @lesson.lesson_questions.find_by(:id => question_lesson.id).end_time.nil? %>
                          <%= @lesson.lesson_questions.find_by(:id => question_lesson.id).end_time %>
                      <% else %>
                          <%= @lesson.lesson_questions.find_by(:id => question_lesson.id).end_time.strftime(" %Y /  %m / %d - %H:%M:%S ") %>
                      <% end %>
                    </td>
                <% end %>
              </tr>
          <% end %>
        </table>
      </div>
    <% end %>
  <% end %>
</div>
<% flash[:previous] = 'questions' %>

app/views/questions/_question_internet_check_show.html.erb
<% title_nil_exist = 0 %>
<% http_error_exist = 0 %>
<% key_word_change = 0 %>
<% checked_result = InternetCheckResult.where(:answer_id =>answer.id )%>
<% if checked_result.count != 0 %>
    <% if checked_result.where(:key_word => question_keyword).count == 0 %>
        <% key_word_change = 1 %>
    <% end %>
<% end %>

<% nil_title = InternetCheckResult.where(:answer_id =>answer.id, :title => nil, :link => nil, :content => nil )%>
<% if nil_title.present? && nil_title.count > 0 %>
    <% title_nil_exist = 1 %>
<% end %>

<% http_error = InternetCheckResult.where(:answer_id =>answer.id, :title => nil, :link => '', :content => '' )%>
<% if http_error.present? && http_error.count > 0 %>
    <% http_error_exist = 1 %>
<% end %>
<% if plagiarism_have_keyword == 1 %>
    <% if title_nil_exist == 1 && http_error_exist == 0 %>
        <a class="btn btn-default disabled" >チェック中</a>
    <% elsif title_nil_exist == 1 && http_error_exist == 1 %>
        <a class="btn btn-default draw_fancybox" href="#internet_results_checked_question_<%=student.id%>" >表示</a>
    <% elsif  key_word_change == 1 %>
        <span>
          <%= button_to "チェック", lessons_internet_check_path(:lesson_id => lesson.id,
                                                            :student_id => student.id,
                                                            :question_id => question.id),
                        {:remote => true , :method => "post", :id => "question_ajax_link_#{student.id}",:class=>"btn btn-default", :data => { :disable_with => "チェック中" } }%>
          <a id="question_display_<%=student.id%>" class="btn btn-default draw_fancybox draw_fancybox_hidden" href="#internet_check_results_<%=student.id %>" >表示</a>
        </span>
    <%else %>
        <% if checked_result.size > 0 && title_nil_exist == 0 && http_error_exist == 0 %>
            <a class="btn btn-default draw_fancybox" href="#internet_results_checked_question_<%=student.id%>" >表示</a>
        <% elsif RESULT[answer.result].to_s.present? && answer.result== 'A'  %>
            <span>
              <%= button_to "チェック", lessons_internet_check_path(:lesson_id => lesson.id,
                                                                :student_id => student.id,
                                                                :question_id => question.id),
                            {:remote => true , :method => "post", :id => "question_ajax_link_#{student.id}",:class=>"btn btn-default", :data => { :disable_with => "チェック中" } }%>
              <% if http_error_exist !=1 %>
                  <a id="question_display_<%=student.id%>" class="btn btn-default draw_fancybox draw_fancybox_hidden" href="#internet_check_results_<%=student.id %>" >表示</a>
              <% elsif http_error_exist == 1 && checked_result.size > 0 %>
                  <a class="btn btn-default draw_fancybox" href="#internet_results_checked_question_<%=student.id%>" >表示</a>
              <% end %>
            </span>
        <% end %>
    <% end %>
<% end %>
<div id="internet_results_checked_question_<%=student.id%>" class="internet-check-results-css" >
    <%= render :partial => "lessons/student_internet_check_result_show", :locals => {:student => student,
                                                                                     :question => @question,
                                                                                     :http_error_exist => http_error_exist,
                                                                                     :checked_result => checked_result } %>
</div>

app/views/questions/_upload_form.html.erb
<h3 id="answer">投稿</h3>
<%= form_tag({:controller => "answers", :action =>  "create"}, :remote=> (@lesson.id!=1), :authenticity_token => true, :multipart => true) do %>
  <div class="answer form-group" name="answer">
    <div class="answer form-group" name="language">
      <%= label_tag :language, '使用言語' %>
      <%= select_tag :language, options_for_select(@languages), :class => 'form-control', :style => 'width:220px' %>
    </div>
    <div class="answer form-group" name="upload_form">
      <%= label_tag :upload_file, 'ファイル選択' %>
      <%= file_field_tag :upload_file, :disabled => (@latest_answer.result == "P" unless @latest_answer.nil?) %>
      <p class="help-block">ファイルサイズは10MBまで</p>
    </div>
    <%= submit_tag 'アップロード', :class => 'btn btn-primary', :disabled => (@latest_answer.result == "P" unless @latest_answer.nil?) %>
  </div>
<% end %>

app/views/questions/create.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/index')) %>");

app/views/questions/destroy.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/index')) %>");

app/views/questions/edit.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/edit')) %>");

app/views/questions/get_exist_question.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/refer_question')) %>");

app/views/questions/index.html.erb
<%= render "questions/index" %>

app/views/questions/index.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/index')) %>");

app/views/questions/new.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/new')) %>");

app/views/questions/update.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/index')) %>");