config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons do
    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy], param: :question_id, :constraints => OnlyAjaxRequest do
      member do
        get '/answers' => 'answers#index', :constraints => OnlyAjaxRequest
      end
    end
    resources :students, only: [] do
      scope '/questions/:question_id' do
        resources :answers, only: [:index]
      end
    end
    collection do
      get '/join' => 'user_lessons#new'
      post '/join' => 'user_lessons#create'
      get ':lesson_id/students' => 'lessons#students', as: 'students', :constraints => OnlyAjaxRequest
      get ':lesson_id/students/:student_id' => 'lessons#student', as: 'student', :constraints => OnlyAjaxRequest
    end
  end

  scope :ajax do
    get 'answers/select_version' => 'answers#select_version'
    get 'lessons/tab_back_home' => 'lessons#tab_back_home'
    post 'answers/diff_select' => 'answers#diff_select'
    post 'lessons/internet_check' =>'lessons#internet_check'
    post 'questions/get_exist_question' => 'questions#get_exist_question'
  end

  get '/public_questions' => 'questions#public_questions', :as => 'questions'
  resources :questions, only: [:show], param: :question_id do
    member do
      get '/answers' => 'answers#index'
    end
  end
  resources :answers, only: [:create]

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  scope :help, :as => :help do
    get '/' => 'help#index'
    get '/index' => 'help#index'
    get '/user_create' => 'help#user_create'

    get '/student_attend_lesson' => 'help#student_attend_lesson'
    get '/student_view_question' => 'help#student_view_question'
    get '/student_answer' => 'help#student_answer'
    get '/student_result' => 'help#student_result'

    get 'teacher_lesson_create' => 'help#teacher_lesson_create'
    get 'teacher_question_create' => 'help#teacher_question_create'
    get 'teacher_view_answer' => 'help#teacher_view_answer'
    get 'teacher_view_result' => 'help#teacher_view_result'
    get 'teacher_web_plagiarism' => 'help#teacher_web_plagiarism'
    get 'teacher_local_plagiarism' => 'help#teacher_local_plagiarism'

    get 'admin_admin_page' => 'help#admin_admin_page'
    get 'admin_user_roles' => 'help#admin_user_roles'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/answer.rb
# -*- coding: utf-8 -*-
class Answer < ActiveRecord::Base
  # user_id belong
  belongs_to :user, :foreign_key => :student_id

  belongs_to :question, :foreign_key => :question_id
  belongs_to :lesson, :foreign_key => :lesson_id
  belongs_to :lesson_question, :foreign_key => :lesson_question_id

  # user_id validate
  validates :user, :presence => true

  validates :question, :presence => true
  validates :lesson, :presence => true
  validates :lesson_question, :presence => true

  # file_name validate
  validates :file_name, :presence => true,
  :format => {:with => /\A[!-~]{1,255}\z/, :message => 'は適切なフォーマットではありません' }
  validates :language, :presence => true
  validates :run_time, :presence => true
  validates :memory_usage, :presence => true
  validates :question_version, :presence => true
  validates :test_count, :presence => true
  validates :test_passed, :presence => true
  validates :result, :presence => true
  validates :local_plagiarism_percentage, :presence => true


  has_many :internet_check_results, :foreign_key => :answer_id
  has_many :local_check_results, :foreign_key => :answer_id
  # 最新の解答を取得
  # @param [Fixnum] student_id
  # @param [Fixnum] lesson_id
  # @param [Fixnum] question_id
  def self.latest_answer(student_id:, lesson_id:, question_id:, lesson_question_id:)
    answers = Answer.where(:student_id => student_id,
                           :question_id => question_id,
                           :lesson_id => lesson_id,
                           :lesson_question_id => lesson_question_id)
    latest_answer = nil
    unless answers.empty?
      last = answers.where(:result => ["A", "P"]).last
      latest_answer = last.nil? ? answers.last : last
    end
    return latest_answer
  end

  # 最新のAcceptの解答を取得
  # @param [Fixnum] student_id
  # @param [Fixnum] lesson_id
  # @param [Fixnum] question_id
  def self.accept_answer(student_id:, lesson_id:, question_id:, lesson_question_id:)
    return Answer.where(:student_id => student_id,
                        :question_id => question_id,
                        :lesson_id => lesson_id,
                        :result => "A",
                        :lesson_question_id => lesson_question_id).last
  end

  # 該当する授業と学生の成績を取得
  # @param [Fixnum] student_id
  # @param [Fixnum] lesson_id
  def self.records(student_id:, lesson_id:, lesson_questions:nil)
    lesson_questions = lesson_questions ? lesson_questions : LessonQuestion.where(:lesson_id => lesson_id)
    accept_count = 0

    lesson_questions.each do |lesson_question|
      answer = Answer.accept_answer(:student_id => student_id,
                                    :lesson_id => lesson_id,
                                    :question_id => lesson_question.question_id,
                                    :lesson_question_id => lesson_question.id)
      if answer.present?
        accept_count += 1
      end
    end
    return accept_count
  end

  # 入力されたlanguageが正しいかどうかの検証
  def include_language
    unless LANGUAGE.include?(language.camelize)
    end
  end

  # TODO: controllerの登録でカスタマイズが可能?
  # https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/edit.rb
  # TODO: createアクションは必要だろうか？
  rails_admin do
    weight 4
    create do
      field :user do
        required true
      end
      field :question do
        required true
      end
      field :lesson do
        required true
      end
      field :lesson_question_id, :enum do
        enum do
          LessonQuestion.all.collect {|lq| ["[#{lq.lesson.name}] - [#{lq.question.title}] ##{lq.id}", lq.id]}
        end
        required true
        help "解答した問題と授業の関連, コピーした問題がある場合は注意, #{help}"
      end
      field :file_name do
        required true
        help "サーバに保存した解答ソースコードのファイル名, #{help}"
      end
      field :language, :enum do
        required true
        enum do
          LANGUAGES.collect { |l| ["#{l}", l.downcase]}
        end
      end
      field :run_time do
        help "単位はms, #{help}"
      end
      field :memory_usage do
        help "単位はMB, #{help}"
      end
      field :question_version do
        required true
        help "解答した問題のバージョン, #{help}"
      end
      field :test_count
      field :test_passed
      field :result, :enum do
        required true
        help "評価結果, #{help}"
        enum do
          RESULT.collect {|k,v| ["#{v}", k]}
        end
      end
    end

    edit do
      field :user do
        required true
      end
      field :question do
        required true
      end
      field :lesson do
        required true
      end
      field :lesson_question_id, :enum do
        enum do
          LessonQuestion.all.collect {|lq| ["[#{lq.lesson.name}] - [#{lq.question.title}] ##{lq.id}", lq.id]}
        end
        required true
        help "解答した問題と授業の関連, コピーした問題がある場合は注意, #{help}"
      end
      field :file_name do
        read_only true
        help "サーバに保存した解答ソースコードのファイル名"
      end
      field :language, :enum do
        required true
        enum do
          LANGUAGES.collect { |l| ["#{l}", l.downcase]}
        end
      end
      field :run_time do
        help "単位はms, #{help}"
      end
      field :memory_usage do
        help "単位はMB, #{help}"
      end
      field :question_version do
        required true
        help "解答した問題のバージョン, #{help}"
      end
      field :test_count
      field :test_passed
      field :result, :enum do
        required true
        help "評価結果, #{help}"
        enum do
          RESULT.collect {|k,v| ["#{v}", k]}
        end
      end
      field :local_plagiarism_percentage do
        help "学生間のソースコードの類似度, #{help}"
      end
      field :internet_check_results do
        help "Web上のソースコードとの類似度"
      end
    end

    list do
      field :id
      field :user
      field :question
      field :lesson
      field :lesson_question do
        pretty_value do
          val = "[#{value.lesson.name}] - [#{value.question.title}] : ##{value.id}"
          bindings[:view].link_to val, bindings[:view].rails_admin.show_path('lesson_question', value.id)
        end
      end
      field :result do
        formatted_value do
          RESULT[value]
        end
      end
      field :file_name
      field :language
      field :run_time
      field :memory_usage
      field :question_version
      field :test_countn
      field :test_passed
      field :local_plagiarism_percentage
      field :internet_check_results
      field :created_at
      field :updated_at
    end

    show do
      field :id
      field :user
      field :question
      field :lesson
      field :lesson_question do
        pretty_value do
          val = "[#{value.lesson.name}] - [#{value.question.title}] : ##{value.id}"
          bindings[:view].link_to val, bindings[:view].rails_admin.show_path('lesson_question', value.id)
        end
      end
      field :result do
        formatted_value do
          RESULT[value]
        end
      end
      field :file_name
      field :language
      field :run_time
      field :memory_usage
      field :question_version
      field :test_count
      field :test_passed
      field :local_plagiarism_percentage
      field :internet_check_results
      field :created_at
      field :updated_at
    end
  end

end

app/controllers/answers_controller.rb
# -*- coding: utf-8 -*-
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def index
    @student_id = params[:student_id] || current_user.id
    @lesson_id = params[:lesson_id] || session[:lesson_id] || 1
    @question_id = params[:question_id] || session[:question_id]
    lesson_question_id = params[:lesson_question_id] || session[:lesson_question_id]
    @question = Question.find_by(:id => @question_id)
    if Lesson.find_by(:id => @lesson_id).nil? || Question.find_by(:id => @question_id).nil? || User.find_by(:id => @student_id).nil?
      redirect_to root_path, :alert => '該当する解答は存在しません' and return
    end
    unless params[:student_id].nil?
      @is_teacher = Lesson.find_by(:id => @lesson_id).user_lessons.find_by(:user_id => current_user.id, :lesson_id => @lesson_id)

      # 該当授業の教師かどうかを取得
      if @is_teacher.nil?
        redirect_to root_path, :alert => '該当する授業に参加していません' and return
      end
      @is_teacher = @is_teacher.is_teacher
      unless @is_teacher
        redirect_to root_path, :alert => '該当する解答は存在しません' and return
      end
    end

    @answer_all_version= Answer.where(:question_id => @question_id,
                                      :lesson_id=> @lesson_id,
                                      :lesson_question_id => lesson_question_id,
                                      :student_id=> @student_id )

    @dead_date_question = LessonQuestion.find_by(:id => lesson_question_id)

    @raw_display_file  = @answer_all_version.last.file_name

    @path_directory = UPLOADS_ANSWERS_PATH.join(@student_id.to_s, lesson_question_id.to_s).to_s + "/"
    flash[:directory]= @path_directory

    @new_raw_path = @path_directory + @raw_display_file
  end

  # post '/answers'
  # @param [Binary] upload_file アップロードファイル
  # @param [language] language 選択言語
  # @param [Fixnum] lesson_id
  # @param [Fixnum] id Questionのid
  def create
    file = params[:upload_file]
    lesson_question_id = session[:lesson_question_id]
    question_id = session[:question_id]
    lesson_id = session[:lesson_id].present? ? session[:lesson_id] : 1

    # ajax用の変数
    @lesson = Lesson.find_by(:id => lesson_id)
    @question = Question.find_by(:id => question_id)
    @is_teacher = Lesson.find_by(:id => lesson_id).user_lessons.find_by(:user_id => current_user.id, :lesson_id =>lesson_id).is_teacher
    @languages = LANGUAGES.map { |val| [val, val.downcase] }.to_h

    # ファイルが選択されている場合
    unless file.nil?
      extention = EXT[params[:language]]
      name = file.original_filename

      # ファイルのチェック
      if !(extention == File.extname(name).downcase)
        flash.now[:alert] = '使用言語とファイル拡張子が一致しません。'
      elsif file.size > 10.megabyte
        flash.now[:alert] = 'ファイルサイズは10MBまでにしてください。'
      else

        # 保存ディレクトリの作成
        uploads_answers_path = UPLOADS_ANSWERS_PATH.join(current_user.id.to_s, lesson_question_id.to_s)
        FileUtils.mkdir_p(uploads_answers_path) unless FileTest.exist?(uploads_answers_path)

        # 最後の解答のファイル名の取得
        old_file = Answer.where(:lesson_id => lesson_id,
                                :student_id => current_user.id,
                                :lesson_question_id => lesson_question_id,
                                :question_id => question_id).last
        /\d+/ =~ old_file.file_name unless old_file.nil?
        version = $&.to_i
        next_version = (version + 1).to_s
        next_name = "version#{next_version}#{extention}"

        # ファイルの保存
        File.open("#{uploads_answers_path}/#{next_name}", 'wb') do |f|
          f.write(file.read)
        end

        # Answerモデルの保存
        answer = Answer.new(:language => params[:language],
                            :question_id => question_id,
                            :lesson_id => lesson_id,
                            :lesson_question_id => lesson_question_id,
                            :file_name => next_name,
                            :result => "P",
                            :student_id => current_user.id,
                            :run_time => 0,
                            :memory_usage => 0,
                            :question_version =>@question.version)
        unless answer.save
          flash.now[:notice] = "解答の保存に失敗しました．" and return
        end
        @latest_answer = answer
        flash.now[:notice] = '解答を投稿しました。'

        # 評価スクリプトをメッセージキューに入れる
        case params[:language]
        when 'python'
          EvaluatePythonJob.perform_later(:user_id => current_user.id,
                                          :lesson_id => lesson_id,
                                          :question_id => question_id,
                                          :lesson_question_id => lesson_question_id)
        when 'c', 'cpp'
          EvaluateCJob.perform_later(:user_id => current_user.id,
                                     :lesson_id => lesson_id,
                                     :question_id => question_id,
                                     :lesson_question_id => lesson_question_id)
        end
      end

      # ファイルが選択されていなかった場合
    else
      @latest_answer = Answer.latest_answer(:student_id => current_user.id,
                                            :question_id => question_id,
                                            :lesson_id => lesson_id,
                                            :lesson_question_id => lesson_question_id) || nil
      flash.now[:alert] = 'ファイルが選択されていません。'
    end

    # パブリック授業の場合
    if @lesson.id == 1
      redirect_to :controller => 'questions', :action => 'show',  :question_id => question_id
    end
  end

  def select_version
    @select_item = params[:selected_file]
    @select_path = flash[:directory]
    @new_raw_path = @select_path.to_s + @select_item
    flash[:directory] = flash[:directory]
  end

  def diff_select
    flash[:directory] = flash[:directory]
    @select_diff_file = params[:diff_selected_file]
    @select_raw_file = params[:raw_selected_file]

    @select_raw_name = flash[:directory].to_s + @select_raw_file
    if @select_diff_file == "なし"
      return
    end

    select_diff_name = flash[:directory].to_s + @select_diff_file
    @diff = show_diff(@select_raw_name, select_diff_name)
  end


  private
  def show_diff(original_file, new_file)
    file = "./tmp/" + Digest::MD5.hexdigest(DateTime.now.to_s + rand.to_s) + ".txt"
    output = `diff -t --new-line-format='+%L' --old-line-format='-%L' --unchanged-line-format=' %L' #{original_file} #{new_file} > #{file}`
    diff = File.open("#{file}", 'r:utf-8')
    `rm #{file}`
    return diff
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def remove_head(str)
    str.slice!(0) if str.chars[0] == "-" || str.chars[0] == "+"
    return str
  end

  def th_color(sign)
    if sign == "+"
      return "green"
    elsif sign == "-"
      return "red"
    else
      return "normal"
    end
  end
end

app/views/answers/_diff_select.html.erb
<table class="diff">

  <% if @select_diff_file != "なし" %>
      <tr class="head">
        <th class="old_line"> Selected </th>
        <th class="new_line"> Compared </th>
        <th class="change"> </th>
        <th id="code"> Source Code </th>
      </tr>
      <% old_line_number = 0 %>
      <% new_line_number = 0 %>
      <% @diff.each_with_index do |line, i| %>
          <% old_line_number += 1 %>
          <% new_line_number += 1 %>
          <tr class=" <%= th_color(line.chars[0]) %>">
            <% if line.chars[0] == "+" %>
                <% old_line_number -= 1 %>
                <td class="old_line"> </td>
                <td class="new_line"> <%= new_line_number %> </td>
            <% elsif line.chars[0] == "-" %>
                <% new_line_number -= 1 %>
                <td class="old_line"> <%= old_line_number %> </td>
                <td class="new_line"> </td>
            <% else %>
                <td class="old_line"> <%= old_line_number %> </td>
                <td class="new_line"> <%= new_line_number %> </td>
            <% end %>
            <td class="change"> <%= line.chars[0] %> </td>
            <td><pre id="code"> <%= remove_head(line).chomp %> </pre></td>
          </tr>
      <% end %>
  <% else %>
      <tr class="head">
        <th class="old_line">Lines</th>
        <th id="code">Source Code</th>
      </tr>
      <% File.open(@select_raw_name, 'r:utf-8') do |f| %>
          <% f.each_with_index do |line,i| %>
              <tr>
                <td class="old_line"> <%=  i+1 %></td>
                <td style="width:100%"><pre id="code"> <%= line.chomp %></pre> </td>
              </tr>
          <% end %>
      <% end %>
  <% end %>

</table>

app/views/answers/_index.html.erb
<div>
  <% if @lesson_id.to_i == 1 %>
    <% if flash[:previous] == "question" %>
      <%= button_to '問題詳細に戻る', question_path(:question_id => @question_id), :method => 'get',:class => "btn btn-default btn_top" %>
    <% elsif flash[:previous] == "questions" %>
      <%= button_to '問題一覧に戻る', questions_path, :method => 'get', :class => "btn btn-default btn_top" %>
    <% end %>
  <% else %>
    <% if flash[:previous] == "question" %>
      <%= button_to '問題詳細に戻る', lesson_question_path(:lesson_id => @lesson_id, :question_id => @question_id), :method => 'get',
           :remote => true, :class => "btn btn-default btn_top" %>
    <% elsif flash[:previous] == "questions" %>
      <%= button_to '問題一覧に戻る', lesson_questions_path(:lesson_id => @lesson_id), :remote => true, :method => 'get', :class => "btn btn-default btn_top" %>
    <% elsif flash[:previous] == "student" %>
      <%= button_to '学生詳細に戻る', student_lessons_path(:lesson_id => @lesson_id, :student_id => params[:student_id]), :method => 'get',
           :remote => true, :class => "btn btn-default btn_top" %>
    <% end %>
  <% end %>
</div>
<div>
  <h2>解答詳細</h2>
  <% if @is_teacher %>
    <h4>ニックネーム: <%= User.find_by(:id => @student_id).nickname %></h4>
  <% end %>
  <div class="questions_list">
    <div>
      <h3><%= @question.title %></h3>
    </div>
    <div>
      <div style="float:right;"><p>問題変更前の回答です</p></div>
      <div style="float:right;"><div class="old_version_color_block"></div></div>
    </div>
    <table class="table table-bordered table-striped">
      <tr>
        <th>バージョン</th>
        <th>提出時間</th>
        <th>結果</th>
        <th>実行時間(ms)</th>
        <th>メモリ使用量(MB/KB)</th>
        <th>使用言語</th>
        <th>開始時間</th>
        <th>終了時間</th>
        <th>正解数</th>
        <% if @is_teacher %>
          <th>学生類似度</th>
        <% end %>
      </tr>


      <% @answer_all_version.each do |m| %>
          <tr>
            <td><%= link_to m.file_name,  { :action => :select_version, :selected_file => m.file_name }, :remote => true%></td>
            <td><%= m.created_at %></td>
            <% if @question.version == m.question_version %>
                <td ><%=  RESULT[m.result] %></td>
            <% else %>
                <% if RESULT[m.result].to_s.empty?%>
                    <td ><%= RESULT[m.result] %></td>
                <% else %>
                    <td class = "old_version_color"><%= RESULT[m.result] %></td>
                <% end %>
            <% end %>
            <td><%= m.run_time %></td>
            <td>
              <% if m.memory_usage / 1024 == 0 %>
                <%= "#{m.memory_usage} KB" %>
              <% else %>
                <%= "#{m.memory_usage / 1024} MB" %>
              <% end %>
            </td>
            <td><%= m.language.capitalize %></td>
            <td><%= @dead_date_question.start_time%></td>
            <td><%= @dead_date_question.end_time%></td>
            <td><%= "#{m.test_passed} / #{m.test_count}" %></td>
            <% if @is_teacher %>
                <td><%= m.local_plagiarism_percentage %></td>
            <% end %>
          </tr>
      <% end %>
    </table>

  </div>

  <div class ="diff_area_css">
    <p><span>選択したバージョン：</span><text id="select_file_raw"><%= @raw_display_file %></text></p>
    <% if @is_teacher %>
        <p><span>比較するバージョン</span>
          <%= collection_select(:id, :file_name, @answer_all_version, :id, :file_name , {:prompt => "なし"}, {:id => 'diff_select'})%>
        </p>
    <% end %>
    <div id="diff_area" >
      <%= render 'select_version' %>
    </div>
  </div>

</div>
<%= javascript_include_tag "answers/answers.js" %>

app/views/answers/_select_version.html.erb
<table class="diff">
  <tr class="head">
    <th class="old_line">Lines</th>
    <th id="code">Source Code</th>
  </tr>
  <% File.open(@new_raw_path, 'r:utf-8') do |f| %>
      <% f.each_with_index do |line , i| %>
          <tr>
            <td class="old_line"> <%=  i+1 %></td>
            <td style="width:100%"><pre id="code"> <%= line.chomp %> </pre></td>
          </tr>
      <% end %>
  <% end %>
</table>

app/views/answers/create.js.erb
$("#tab2").html("<%= escape_javascript(render(:partial => 'questions/show')) %>");

app/views/answers/diff_select.js.erb
$('#diff_area').html(
        "<%= escape_javascript(render 'diff_select') %>"
);

app/views/answers/index.html.erb
<%= render "answers/index" %>

app/views/answers/index.js.erb
$('a[data-toggle="tab"]').each(function(i){

    if($(this).parent().attr("class") == 'active'){
        if($(this).text() == "問題"){
            $("#tab2").html("<%= escape_javascript(render(:partial => 'answers/index')) %>");
        }
        if ($(this).text() == "学生"){
            $("#tab3").html("<%= escape_javascript(render(:partial => 'answers/index')) %>");
        }
    }
});

app/views/answers/select_version.js.erb
$('#select_file_raw').html(
        "<%= @select_item %>"
);
$('#diff_area').html(
        "<%= escape_javascript(render 'select_version') %>"
);

app/views/answers/show.html.erb
<div>
  <h2>学生解答詳細</h2>
  <div class="questions_list">
    <div>
      <h3>問題<%= @question_id %></h3>
    </div>
    <table class="table table-striped">
      <tr>
        <th>バージョン</th>
        <th>提出時間</th>
        <th>結果</th>
        <th>実行時間</th>
        <th>消耗メモリ</th>
        <th>言語</th>
        <th>開始時間</th>
        <th>終了時間</th>
        <th>学生類似度</th>
        <th>WEB類似度</th>
      </tr>

      <% @question_diff_detail.each do |m| %>
          <tr>
            <td><%= m.file_name %></td>
            <td><%= m.created_at %></td>
            <td><%= m.result %></td>
            <td><%= m.run_time %></td>
            <td><%= m.memory_usage %></td>
            <td><%= m.language %></td>
            <td><%= @dead_date_question.start_time%></td>
            <td><%= @dead_date_question.end_time%></td>
            <td><%= m.plagiarism_percentage %></td>
            <td><%=  %></td>
          </tr>
      <% end %>
    </table>

  </div>
  <div class="diff_area">
    <form>
      <%= collection_select(:id, :file_name, @question_diff_detail, :id, :file_name ,{:prompt => "比べ元を選択してください"},{:class=>'my-custom-class'})%>
      <%= collection_select(:id, :file_name, @question_diff_detail, :id, :file_name ,{:prompt => "比べ先を選択してください"},{:class=>'my-custom-class'}) %>
    </form>
    <div>
      <% @select_item = "abc"%>
      <%= text_area :page, :name, :value=> @select_item, :rows=>30 , :class=>"form-control" %>
    </div>

  </div>

</div>