config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons do
    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy], param: :question_id, :constraints => OnlyAjaxRequest do
      member do
        get '/answers' => 'answers#index', :constraints => OnlyAjaxRequest
      end
    end
    resources :students, only: [] do
      scope '/questions/:question_id' do
        resources :answers, only: [:index]
      end
    end
    collection do
      get '/join' => 'user_lessons#new'
      post '/join' => 'user_lessons#create'
      get ':lesson_id/students' => 'lessons#students', as: 'students', :constraints => OnlyAjaxRequest
      get ':lesson_id/students/:student_id' => 'lessons#student', as: 'student', :constraints => OnlyAjaxRequest
    end
  end

  scope :ajax do
    get 'answers/select_version' => 'answers#select_version'
    get 'lessons/tab_back_home' => 'lessons#tab_back_home'
    post 'answers/diff_select' => 'answers#diff_select'
    post 'lessons/internet_check' =>'lessons#internet_check'
    post 'questions/get_exist_question' => 'questions#get_exist_question'
  end

  get '/public_questions' => 'questions#public_questions', :as => 'questions'
  resources :questions, only: [:show], param: :question_id do
    member do
      get '/answers' => 'answers#index'
    end
  end
  resources :answers, only: [:create]

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  scope :help, :as => :help do
    get '/' => 'help#index'
    get '/index' => 'help#index'
    get '/user_create' => 'help#user_create'

    get '/student_attend_lesson' => 'help#student_attend_lesson'
    get '/student_view_question' => 'help#student_view_question'
    get '/student_answer' => 'help#student_answer'
    get '/student_result' => 'help#student_result'

    get 'teacher_lesson_create' => 'help#teacher_lesson_create'
    get 'teacher_question_create' => 'help#teacher_question_create'
    get 'teacher_view_answer' => 'help#teacher_view_answer'
    get 'teacher_view_result' => 'help#teacher_view_result'
    get 'teacher_web_plagiarism' => 'help#teacher_web_plagiarism'
    get 'teacher_local_plagiarism' => 'help#teacher_local_plagiarism'

    get 'admin_admin_page' => 'help#admin_admin_page'
    get 'admin_user_roles' => 'help#admin_user_roles'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/lesson.rb
# -*- coding: utf-8 -*-
class Lesson < ActiveRecord::Base
  validates :name, :presence => true

  validates :lesson_code, :presence => true, :uniqueness => true,
  :format => {:with => /\A[!-~]{1,255}\z/, :message => 'は適切なフォーマットではありません' }

  has_many :questions

  has_many :user_lessons, :foreign_key => :lesson_id
  has_many :users, :through => :user_lessons

  has_many :lesson_questions, :foreign_key => :lesson_id
  has_many :questions, :through => :lesson_questions

  has_many :answers, :foreign_key => :lesson_id


  rails_admin do
    weight 2
    show do
      field :description
      field :lesson_code
      # TODO: teacherの表示
      field :users
      field :questions
    end

    create do
      field :name do
        required true
      end
      field :description
      field :lesson_code do
        required true
        help "学生が授業に参加する際に入力するコード, #{help}"
      end
      field :users do
        help "ここでは参加する学生を設定できます．この授業を担当する教員は別途「授業の参加」から作成してください，#{help}"
      end
      field :questions
    end

    edit do
      field :name do
        required true
      end
      field :description
      field :lesson_code do
        required true
        help "授業に参加するためのコード, #{help}"
      end
      field :users
      field :questions
    end

    list do
      field :id
      field :name
      field :description
      field :lesson_code
      field :users do
        help "ここでは参加する学生を設定できます．この授業を担当する教員は別途「授業の参加」から作成してください，#{help}"
      end
      field :questions
      field :created_at
      field :updated_at
    end
  end
end

app/controllers/lessons_controller.rb
# -*- coding: utf-8 -*-
class LessonsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :check_lesson, only: [:show, :students]
  before_action :init

  # get '/'
  def index
    session[:lesson_id]=nil
    if current_user.nil?
      redirect_to new_user_session_path
    end
  end

  # get '/lessons/new'
  def new
    @lesson = Lesson.new

    #教師の資格があるかどうかを確認する
    unless(User.find_by(:id => current_user.id).has_role?(:teacher))
      redirect_to root_path, :alert => "あなたはこの権限がありません" and return
    end
  end

  # post '/lessons'
  # クラスの作成
  def create
    @lesson = Lesson.new(params_lesson)
    @user_lesson = UserLesson.new
    @user_lesson.user_id = current_user.id

    #誤り検出のアルゴリズムLuhnを使って授業コードを生成する
    lesson_code = Array.new(10) { rand(10) }.join
    lesson_code + Luhn.checksum(lesson_code).to_s
    @lesson.lesson_code = lesson_code

    if @lesson.name !=''
      if @lesson.save
        #Teacherの情報をuser_lessonに記入する
        @user_lesson.lesson_id = @lesson.id
        @user_lesson.is_teacher = true
        @user_lesson.save

        flash.notice  = 'クラスを作成しました！'
        redirect_to  :action =>'show', :id=> @lesson.id

      else
        flash.notice  = 'クラスの作成に失敗しました！'
        render action: 'new'
      end
    else
      render action: 'new'
      flash.notice = 'クラス名を入力してください！'
    end


  end

  def edit
    lesson_id = params[:id]
    @lesson = Lesson.find(lesson_id)
  end

  def update
    @lesson_id = params[:id]
    @lesson = Lesson.find(@lesson_id)
    @lesson.name= params[:lesson][:name]
    @lesson.description = params[:lesson][:description]
    if @lesson.save
      flash.now[:notice] = '授業を更新しました'
    else
      flash.now[:notice] = '授業の更新に失敗しました'
    end

    #Ajax
    @teachers = get_teachers
    @is_teacher = @lesson.user_lessons.find_by(:user_id => current_user.id, :lesson_id => @lesson.id).is_teacher
    session[:lesson_id] = params[:id] || session[:lesson_id]
    private_lesson = UserLesson.where(:lesson_id => params[:id],:is_deleted =>true).last
    session[:seleted_lesson]=nil
    if private_lesson.present?
      session[:seleted_lesson] = "private_lesson"
    end

  end

  def destroy
    lesson_id = params[:lesson_id]
    deleted_lesson = UserLesson.where(:lesson_id =>lesson_id)
    deleted_lesson.update_all(:is_deleted => true)
  end

  # get '/lessons/:id'
  def show
    @teachers = get_teachers
    @is_teacher = @lesson.user_lessons.find_by(:user_id => current_user.id, :lesson_id => @lesson.id).is_teacher
    session[:lesson_id] = params[:id] || session[:lesson_id]
    private_lesson = UserLesson.where(:lesson_id => params[:id],:is_deleted =>true).last
    session[:seleted_lesson]=nil
    if private_lesson.present?
      session[:seleted_lesson] = "private_lesson"
    end
  end

  def tab_back_home
    @lesson_id = params[:lesson_id]
    @lesson = Lesson.find(@lesson_id)
    #Ajax
    @teachers = get_teachers
    @is_teacher = @lesson.user_lessons.find_by(:user_id => current_user.id, :lesson_id => @lesson.id).is_teacher
    session[:lesson_id] = @lesson_id || session[:lesson_id]
    private_lesson = UserLesson.where(:lesson_id => @lesson_id,:is_deleted =>true).last
    session[:seleted_lesson]=nil
    if private_lesson.present?
      session[:seleted_lesson] = "private_lesson"
    end
  end

  # get '/lessons/:id/students'
  def students
    @students = get_students
    @lesson_questions_count = @lesson.lesson_questions.count
  end

  # get '/lessons/:id/students/:student_id'
  def student
    @lesson_id = params[:lesson_id]
    @student_id = params[:student_id]
    @student = User.find_by(:id => @student_id )
    @lesson_questions = LessonQuestion.where(:lesson_id => @lesson_id)
  end

  # source code check through internet
  def internet_check
    @result = Array.new(0,Array.new(5,0))
    @multi_check = 0
    #get data from ajax
    @question_id = params[:question_id]
    @student_id = params[:student_id]
    @lesson_id = params[:lesson_id]
    lesson_question_id = LessonQuestion.where(:lesson_id=>@lesson_id, :question_id => @question_id).last.id

    @question = Question.find_by(:id => @question_id)
    @lesson = Lesson.find_by(:id => @lesson_id)

    question_keyword =''
    question_keywords = QuestionKeyword.where(:question_id => @question_id)
    question_keywords.each do |k|
      question_keyword = question_keyword + " " + k['keyword']
    end

    if @student_id.to_i != 0
      @student = User.find_by(:id => @student_id)
      answer = Answer.where(:lesson_id => @lesson_id, :student_id => @student_id, :question_id => @question_id, :lesson_question_id => lesson_question_id).last
      #「Http error , Api 使用できない」原因で保存した　臨時データを削除
      http_error = InternetCheckResult.where(:answer_id =>answer.id, :title => nil, :link => '', :content => '' )
      if http_error.present?
        http_error.each do |r|
          if r['answer_id'] == answer.id
            r.destroy
          end
        end
      end

      @check_result = InternetCheckResult.where(:answer_id => answer.id)
      #key word の変更したかどうかを確認する
      #変更した場合、前回の結果を削除する
      @check_result.each do |r|
        if r['key_word'] != question_keyword
          r.destroy
        end
      end

      @check_result_count = @check_result.count

      if @check_result_count != 0   # 既に検索結果あり,keyword変更なし
        return
      end

      init_result = InternetCheckResult.new(:answer_id => answer.id, :title => nil, :link => nil, :content => nil, :repeat => 0, :key_word => "" )
      init_result.save
      single_check = PlagiarismInternetCheck.new(@question_id, @lesson_id, @student_id, lesson_question_id,@result)
      single_check.check
    else
      @students = User.where(:id => @lesson.user_lessons.where(:is_teacher => false).pluck(:user_id))
      @multi_check = 1
      @students.each do |s|
        answer = Answer.where(:lesson_id => @lesson_id, :student_id => s['id'], :question_id => @question_id, :lesson_question_id => lesson_question_id).last
        #「Http error , Api 使用できない」原因で保存した　臨時データを削除
        if answer.present?
        http_error = InternetCheckResult.where(:answer_id =>answer.id, :title => nil, :link => '', :content => '' )
        if http_error.present?
          http_error.each do |r|
            if r['answer_id'] == answer.id
              r.destroy
            end
          end
        end
        end

        unless answer.nil?
          check_result = InternetCheckResult.where(:answer_id => answer.id)
          #key word の変更したかどうかを確認する
          #変更した場合、前回の結果を削除する
          check_result.each do |r|
            if r['key_word'] != question_keyword
              r.destroy
            end
          end
          check_result_count = check_result.count
          if check_result_count == 0
            #チェック中を表示するため
            #:title => nil, :link => nil, :content => nil,
            init_result = InternetCheckResult.new(:answer_id => answer.id, :title => nil, :link => nil, :content => nil, :repeat => 0, :key_word => "" )
            init_result.save
          end
        end
      end
      InternetCheckJob.perform_later(@question_id,@lesson_id,lesson_question_id)
    end

  end

  #Luhnアルゴリズムの導入
  def init
    require 'luhn'
  end

  private

  # idまたはlesson_idから該当するLessonを検索
  # @param [Fixnum] lesson_id
  # @param [Fixnum] id 一部のURLでのlesson_id
  def check_lesson
    id = params[:lesson_id] || params[:id]
    return unless access_lesson_check(:user_id => current_user.id, :lesson_id => id)
    @lesson = Lesson.find_by(:id => id)
  end

  # 該当するlessonに所属するstudentを取得
  def get_students
    return User.where(:id => @lesson.user_lessons.where(:is_teacher => false).pluck(:user_id))
  end

  # 該当するlessonに所属するteacherを取得
  def get_teachers
    return User.where(:id => @lesson.user_lessons.where(:is_teacher => true).pluck(:user_id))
  end

  def params_lesson
    params.require(:lesson).permit(:name , :description)
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_edit.html.erb
<h1>授業編集</h1>
<%= form_for(@lesson,:remote=>true ,:url=>lesson_path(:id => params[:id])) do |f| %>
    <%= f.label :name , '授業名'%><span>(<span class="inputnote">＊</span>)</span><br>
    <%= f.text_field :name , :size => 200 , :maxlength => 200,:class => 'text-area-css1', required: 'required' %></br>
    <%= f.label :description , '説明'%><br>
    <%= f.text_area :description , :rows => 10 ,:class => 'text-area-css1'%></br>
    <%= f.hidden_field  :lesson_code  %>
    <%= f.submit  '更新',:class=>'btn btn-primary'  %>
<% end %>

app/views/lessons/_index.html.erb
<%= render "layouts/notice" %>
<div class = "lesson-new">
  <% if current_user.has_role?(:teacher) %>
    <%= link_to '授業作成',{ :controller =>"lessons", :action =>"new"}, :class => 'btn btn-primary'%>
  <% end %>
</div>
<div class="hero-unit">
  <h1>Procsへようこそ!</h1>
  <p>こちらからすべての問題を見ることができます。<br>
    また授業への参加もこちらからできます。</p>
  <p>
    <%= link_to '問題一覧', '/public_questions', class: 'btn btn-primary' %>
    <%= link_to '授業参加', {:controller => :user_lessons, :action => :create}, class: 'btn btn-primary' %>
  </p>
</div>
<% user_lesson = UserLesson.where(:user_id => current_user.id, :is_deleted => false ) %>
<% unless user_lesson.empty? %>
  <% user_lesson.each do |lesson_select_user| %>
    <% next if lesson_select_user.lesson_id == 1 %>
    <div class="hero-unit">
      <h1><%= link_to lesson_select_user.lesson.name, lesson_path(:id => lesson_select_user.lesson.id) %></h1>
      <% if lesson_select_user.is_teacher? %>
        <p><%= lesson_select_user.user.name  %></p>
      <% else %>
        <% owner_lesson = UserLesson.where(:lesson_id => lesson_select_user.lesson_id, :is_teacher => true).last %>
        <p><%= owner_lesson.user.name  %></p>
      <% end %>
      <p><%= simple_format(h(lesson_select_user.lesson.description)) %></p>
    </div>
  <% end %>
<% end %>

<% if current_user.has_role?(:teacher)%>
  <% deleted_lessons = UserLesson.where(:user_id => current_user.id , :is_deleted => true) %>
  <% if deleted_lessons.count > 0 %>
    <div class = "lesson-new">
      <h3><FONT color="#ff0000">非公開授業</FONT></h3>
      <p>非公開授業は学生に表示されません。</p>
      <p>再公開したい場合は、システム管理者に連絡してください。</p>
      <% deleted_lessons.each do |d| %>
        <% next if d.lesson_id == 1%>
        <% session[d.lesson_id] = "lesson_private" %>
        <div class="hero-unit">
          <h1><%= link_to d.lesson.name, lesson_path(:id => d.lesson.id) %></h1>
          <p><%= d.user.name  %></p>
          <p><%= simple_format(h(d.lesson.description)) %></p>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/lessons/_internet_check.html.erb
<div>
  <p>ニックネーム：<%= @student.nickname %></p>
  <p>問題：<%= @question.title %></p>
  <% max_time = 0 %>
  <% http_error_result = 0 %>
  <% if @check_result_count == 0 %>
    <% @result.each do |item|%>
      <% if item[2] > 1 %>
          <% max_time=item[2] %>
          <% break %>
      <% end %>
    <% end %>

    <% if  @result.size >0  %>
      <% len = @result.size %>
      <% if @result[len-1][0] =='http_error' %>
          <% http_error_result = 1 %>
      <% end %>
    <% end %>

    <% if max_time > 1 && http_error_result == 0 %>
      <p>WEB剽窃チェックの結果：解答に関連があるWEBページを検出しました</p>
      <% index=1 %>
      <% @result = @result.sort do |item1,item2| %>
        <% item2[2]<=> item1[2] %>
      <% end %>
      <%@result.each do |item| %>
          <% if index >5 %>
              <% break %>
          <% end %>
          <div class="hero-unit2">
            <p>関連タイトル：<%= item[0] %></p>
            <p>関連リンク：<%= link_to item[1],"#{item[1]}", :target => ["'_blank'"] %></p>
            <p>回数：<%= item[2] %></p>
            <p>内容：<%= item[3] %></p>
          </div>
          <% index +=1 %>
      <% end %>
    <% elsif http_error_result == 1 %>
      <p>剽窃チェックができませんでした。以下の問題が考えられます。</p>
      <p>(1)インターネットの接続に問題がありませんか。</p>
      <p>(2)検索回数の上限を超えてませんか。</p>
      <p>設定を確認したら、再チェックを行なってください。</p>
    <% else %>
      <p>WEB剽窃チェックの結果：解答に関連があるWEBページを検出できませんでした</p>
    <% end %>

  <% else %>
    <% @check_result.each do |r|%>
      <% if r['repeat'] > 1 %>
          <% max_time=r['repeat'] %>
          <% break %>
      <% end %>
    <% end %>
    <% if max_time > 1 %>
      <p>WEB剽窃チェックの結果：解答に関連があるWEBページを検出しました</p>
      <% @check_result.each do |result| %>
          <div class="hero-unit2">
            <p>関連タイトル：<%= result['title'] %></p>
            <p>関連リンク：<%= link_to result['link'],"#{result['link']}", :target => ["'_blank'"] %></p>
            <p>回数：<%= result['repeat'] %></p>
            <p>内容：<%= result['content'] %></p>
          </div>
      <% end %>

    <% else %>
      <p>WEB剽窃チェックの結果：解答に関連があるWEBページを検出できませんでした</p>
    <% end %>

  <% end %>
</div>

app/views/lessons/_lesson_details.html.erb
<%= render "layouts/notice" %>
<%= link_to "授業一覧に戻る" ,root_path , :class => "btn btn-default btn_top "%>
<% if @is_teacher && session[:seleted_lesson] != "private_lesson" %>
    <%= link_to "編集" ,edit_lesson_path(:id => @lesson.id ) , :remote => true, :class => "btn btn-default btn_top " %>
    <button class="btn btn-danger btn_top", id="lesson_delete">非公開</button><span id="lesson_delete_attach", style="visibility: hidden;"><text ><%= @lesson.id %></text></span>
<% end %>
<h1>授業基本情報</h1>
<table class="student">
  <tbody>
  <tr>
    <th>授業名</th>
    <td><%= @lesson.name %></td>
  </tr>
  <tr>
    <th>授業の説明</th>
    <td><%= simple_format(h(@lesson.description)) %></td>
  </tr>
  <tr>
    <th>教員</th>
    <td>
      <% @teachers.each_with_index do |teacher, i| %>
          <%= teacher.name %>
          <% if i + 1 < @teachers.count %>
              ,
          <% end %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>授業コード</th>
    <td><%= @lesson.lesson_code %></td>
  </tr>
  </tbody>
</table>
<%= javascript_include_tag "lessons/delete_lesson" %>

app/views/lessons/_student.html.erb
<script type="text/javascript">

    jQuery(document).ready(function(){
        jQuery(".draw_fancybox").fancybox({
            maxWidth    : 1200,
            maxHeight   : 600,
            fitToView   : false,
            width       : '70%',
            height      : '70%',
            autoSize    : false,
            closeClick  : false,
            openEffect  : 'none',
            closeEffect : 'none'
        });
        jQuery(".draw_fancybox2").fancybox({
            maxHeight   : 600,
            fitToView   : false,
            width       : '90%',
            height      : '90%',
            autoSize    : false,
            closeClick  : false,
            openEffect  : 'none',
            closeEffect : 'none',
        });
    });
</script>
<%= link_to "学生一覧に戻る", students_lessons_path(:lesson_id => params[:lesson_id]), :remote => true , :method => "GET" , :class=>"btn btn-default btn_top" %>
<h1>学生詳細ページ</h1>

  <table class="student">
    <tbody>
      <tr>
        <th>ニックネーム</th>
        <td><%= @student.nickname %></td>
      </tr>
      <tr>
        <th>学籍番号</th>
        <td><%= @student.student_number %></td>
      </tr>
      <tr>
        <th>emailアドレス</th>
        <td><%= @student.email %></td>
      </tr>
    </tbody>
  </table>
<h2>解答状況</h2>
<div>
  <div>
    <div style="float:right;"><p>問題変更前の回答です</p></div>
    <div style="float:right;"><div class="old_version_color_block"></div></div>
  </div>
  <table class="table table-bordered table-striped">
    <tr>
      <th>問題番号</th>
      <th>問題名</th>
      <th>結果</th>
      <th>実行時間(ms)</th>
      <th>メモリ使用量(MB/KB)</th>
      <th>終了時間</th>
      <th>提出</th>
      <th>学生同士の類似度</th>
      <% unless ENV['BING_APIKEY'].nil? %>
      <th>WEB剽窃チェック</th>
      <% end %>
    </tr>
    <% num = 0 %>
    <% @lesson_questions.each do |lesson_question| %>
        <tr>
          <% if lesson_question['is_deleted'] == true  %>
              <% next %>
          <% end %>

          <% num = num + 1 %>
          <% question = Question.find_by(:id => lesson_question.question_id) %>
          <% answer = Answer.latest_answer(:lesson_id => @lesson_id ,:student_id => @student.id ,:question_id => lesson_question.question_id, :lesson_question_id => lesson_question.id) %>
          <td><%= num  %></td>
          <% unless answer.nil? %>
              <td class="table-question-title-css"><%= link_to question.title, lesson_student_answers_path(:lesson_id => @lesson_id,
                                                                          :question_id => question.id,
                                                                          :student_id => @student.id,
                                                                          :lesson_question_id => lesson_question.id),:remote => true  %></td>
              <% if question.version == answer.question_version %>
                  <td><%= RESULT[answer.result] %></td>
              <% else %>
                  <% if RESULT[answer.result].to_s.empty?%>
                      <td ><%= RESULT[answer.result] %></td>
                  <% else %>
                      <td class = "old_version_color"><%= RESULT[answer.result] %></td>
                  <% end %>
              <% end %>
              <td><%= answer.run_time %></td>
              <% if answer.memory_usage / 1024 == 0 %>
                  <td><%= "#{answer.memory_usage} KB" %></td>
              <% else %>
                  <td><%= "#{answer.memory_usage / 1024} MB" %></td>
              <% end %>
              <td><%= lesson_question.end_time %></td>
              <td><%= answer.created_at %></td>
              <!-- ローカル類似度表示 -->
              <td>
                <span>
                  <% unless answer.new_record? %>
                      <% if answer.local_plagiarism_percentage == -1.0 %>
                          <p>実行中...</p>
                      <% else %>
                          <p><%= answer.local_plagiarism_percentage %>%</p>
                          <a class="btn btn-default draw_fancybox2" href="#local_checked_results_<%=lesson_question.question_id %>" >内容を確認</a>
                      <% end %>
                  <% end %>
                </span>
              </td>
              <!-- Localウィンドウ表示内容-->
              <td id="local_checked_results_<%=lesson_question.question_id %>" class="internet-check-results-css" >
                <%= render :partial => "questions/local_check_results", :locals => {:student => @student, :question => question, :answer => answer} %>
              </td>
              <% unless ENV['BING_APIKEY'].nil? %>
                <td>
                  <%= render :partial => "lessons/student_internet_check_show", :locals => {:student => @student,
                                                                                            :question => question,
                                                                                            :answer => answer,
                                                                                            :lesson_id => @lesson_id,
                                                                                            :lesson_question => lesson_question } %>
                </td>
              <% end %>
          <% else %>
              <td class="table-question-title-css"><%= question.title %></td>
              <td><p>-</p></td>
              <td><%= %></td>
              <td><%= %></td>
              <td><%= lesson_question.end_time %></td>
              <td><%= %></td>
              <td><%= %></td>
              <% unless ENV['BING_APIKEY'].nil? %>
              <td>
              </td>
              <% end %>
          <% end %>
        </tr>
    <% end %>

  </table>
</div>
<% flash[:previous] = "student" %>
<%  @lesson_questions.each do |lesson_question| %>
<div id="internet_check_results_<%=lesson_question.question_id %>" class="internet-check-results-css" >
</div>
<% end %>

app/views/lessons/_students.html.erb
<h2>学生一覧</h2>
<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <tr>
      <th>学籍番号</th>
      <th>ニックネーム</th>
      <th>成績</th>
    </tr>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.student_number , student_lessons_path( :lesson_id => params[:lesson_id] , :student_id => student.id),
                :remote => true  %>
        </td>
        <td>
              <%= link_to student.nickname, student_lessons_path( :lesson_id => params[:lesson_id] , :student_id => student.id),
                 :remote => true %>
        </td>
        <td>
          <% accept_count = Answer.records(:student_id => student.id, :lesson_id => params[:lesson_id], :lesson_questions => @lesson.lesson_questions) %>
          <%= "#{accept_count}/#{@lesson_questions_count}"  %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/lessons/edit.js.erb
$("#tab1").html("<%= escape_javascript(render(:partial => 'lessons/edit')) %>");

app/views/lessons/join.html.erb
<h2>授業参加</h2>
<%= form_tag('/lessons/join') do %>
  <div class="field">
    <%= label_tag :lesson_code, "授業コード" %><br />
    <%= text_field_tag :lesson_code %>
  </div>

  <div class="actions">
    <%= submit_tag "参加" %>
  </div>
<% end %>

app/views/lessons/show.html.erb
<div id ="proftab">
  <ul class="nav nav-tabs">
    <li role="presentation" class="active" id = "home_tab"><a>ホーム</a></li>

    <li role="presentation" id = "questions_tab" ><%= link_to  "問題",  lesson_questions_path(:lesson_id =>@lesson.id ),
                                                               :remote => true , :data => { :toggle=>"tab"} %></li>
    <% if @is_teacher %>
        <li role="presentation" id = "students_tab"><%= link_to  "学生",  students_lessons_path(:lesson_id =>@lesson.id ),
                                                                 :remote => true , :data => { :toggle=>"tab"} %></li>
    <% end %>
  </ul>
</div>
<div class="tab-content">
  <div class="tab-pane active" id="tab1">
    <%= render "lessons/lesson_details" %>
  </div>
  <div class="tab-pane" id="tab2">
  </div>
  <div class="tab-pane" id="tab3">
  </div>
</div>
<script>
    $('#home_tab').click(function(){

        var str_url = "/ajax/lessons/tab_back_home";
        $.ajax({
            url: str_url,
            type: "GET",
            data:{
                lesson_id:"<%=@lesson.id %>"
            }
        });
    });
    history.pushState(null, null, null);
    window.addEventListener("popstate", function() {
        history.pushState(null, null, null);
    });
</script>

app/views/lessons/students.js.erb
$("#tab3").html("<%= escape_javascript(render(:partial => 'lessons/students')) %>");

app/views/lessons/tab_back_home.js.erb
$("#tab1").html("<%= escape_javascript(render(:partial => 'lessons/lesson_details')) %>");

app/views/lessons/update.js.erb
$("#tab1").html("<%= escape_javascript(render(:partial => 'lessons/index')) %>");