config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons do
    resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destroy], param: :question_id, :constraints => OnlyAjaxRequest do
      member do
        get '/answers' => 'answers#index', :constraints => OnlyAjaxRequest
      end
    end
    resources :students, only: [] do
      scope '/questions/:question_id' do
        resources :answers, only: [:index]
      end
    end
    collection do
      get '/join' => 'user_lessons#new'
      post '/join' => 'user_lessons#create'
      get ':lesson_id/students' => 'lessons#students', as: 'students', :constraints => OnlyAjaxRequest
      get ':lesson_id/students/:student_id' => 'lessons#student', as: 'student', :constraints => OnlyAjaxRequest
    end
  end

  scope :ajax do
    get 'answers/select_version' => 'answers#select_version'
    get 'lessons/tab_back_home' => 'lessons#tab_back_home'
    post 'answers/diff_select' => 'answers#diff_select'
    post 'lessons/internet_check' =>'lessons#internet_check'
    post 'questions/get_exist_question' => 'questions#get_exist_question'
  end

  get '/public_questions' => 'questions#public_questions', :as => 'questions'
  resources :questions, only: [:show], param: :question_id do
    member do
      get '/answers' => 'answers#index'
    end
  end
  resources :answers, only: [:create]

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  scope :help, :as => :help do
    get '/' => 'help#index'
    get '/index' => 'help#index'
    get '/user_create' => 'help#user_create'

    get '/student_attend_lesson' => 'help#student_attend_lesson'
    get '/student_view_question' => 'help#student_view_question'
    get '/student_answer' => 'help#student_answer'
    get '/student_result' => 'help#student_result'

    get 'teacher_lesson_create' => 'help#teacher_lesson_create'
    get 'teacher_question_create' => 'help#teacher_question_create'
    get 'teacher_view_answer' => 'help#teacher_view_answer'
    get 'teacher_view_result' => 'help#teacher_view_result'
    get 'teacher_web_plagiarism' => 'help#teacher_web_plagiarism'
    get 'teacher_local_plagiarism' => 'help#teacher_local_plagiarism'

    get 'admin_admin_page' => 'help#admin_admin_page'
    get 'admin_user_roles' => 'help#admin_user_roles'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/views/layouts/_header.html.erb
<nav class="navbar  navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Procs", root_path,  class: 'navbar-brand logo' %>
      <% if user_signed_in? %>
        <%= link_to '問題', questions_path, class: 'navbar-brand logo' %>
        <% if current_user.has_role?(:root) || current_user.has_role?(:admin) %>
          <%= link_to '管理画面', '/admin', class: 'navbar-brand logo' %>
        <% end %>
      <% end %>
      <%= link_to 'ヘルプ', help_path, class: 'navbar-brand logo' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname+"さん", '' %></li>
            <% if current_user.has_role?(:root) %>
                <li><%= link_to "権限：システム管理者", '' %></li>
            <% elsif current_user.has_role?(:admin) %>
                <li><%= link_to "権限：管理者", '' %></li>
            <% elsif current_user.has_role?(:teacher)  %>
                <% if session[:lesson_id] ==nil  %>
                    <li><%= link_to "権限：教員", '' %></li>
                <% else %>
                    <% userlesson = UserLesson.find_by(:user_id => current_user.id, :lesson_id => session[:lesson_id] )%>
                    <% unless userlesson.nil? %>
                        <%if userlesson.is_teacher == false && session[:lesson_id] != 1 %>
                            <li><%= link_to "権限：学生", '' %></li>
                        <% else %>
                            <li><%= link_to "権限：教員", '' %></li>
                        <% end %>
                    <% end %>
                <% end %>
            <% elsif current_user.has_role?(:student) %>
                <li><%= link_to "権限：学生", '' %></li>
            <% end %>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'ログイン/新規登録', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_help_sidebar.html.erb
<div class="container">
  <div class="row-fluid">
    <div class="col-xs-3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <ul>
            <% cat_old = nil %>
            <% controller.action_methods.each do |a| %>
              <% unless a == "access_lesson_check" || a == "access_question_check" || a == "index" %>
                <% category = a.match(/(student|teacher|admin).*/) %>

                <% if !category.nil? && category[1].to_s == "admin" %>
                  <% if current_user.nil? || !current_user.has_role?(:admin) %>
                    <% next %>
                  <% end %>
                <% end %>

                <% if !category.nil? && category[1].to_s == "teacher" %>
                  <% if current_user.nil? || !current_user.has_role?(:teacher) %>
                    <% next %>
                  <% end %>
                <% end %>


                <% if !category.nil? && category[1] != cat_old %>
                  <% unless cat_old.nil? %>
          </ul>
          <% end %>
                  <% cat_old = category[1] %>
                  <li><%= t(category[1].capitalize) %></li>
                  <ul>
                <% end %>
<% if category.nil?%>
  <li><%= link_to t("help.#{a}"), "/help/#{a}" %></li>
<% else %>
  <li><%= link_to t("help.#{category[1]}.#{a}"), "/help/#{a}" %></li>
<% end %>
            <% end %>
          <% end %>
            </ul>
        </ul>
      </div>
    </div>
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div>
  <div>
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="#tab1" data-toggle="tab">ホーム</a></li>
      <li role="presentation"><a href="#tab2" data-toggle="tab">問題</a></li>
      <% if current_user.has_roles?([:teacher, :root, :admin]) %>
        <li role="presentation"><a href="#tab3" data-toggle="tab">回答結果</a></li>
      <% end %>
    </ul>
  </div>

  <div class="tab-content">
    <div class="tab-pane fade in active" id="tab1">
      <!--<%= render :template => "lessons/new" %>-->
    </div>
    <div class="tab-pane fade " id="tab2">
      <!--<%= render :template=> "questions/new" %>-->
    </div>
    <% if current_user.has_roles?([:teacher, :root, :admin]) %>
        <div class="tab-pane fade " id="tab3">

        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-warning"><%= alert %></p>
<% end %>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Procs</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body role = "document">
  <%= render 'layouts/header' %>
  <div class="container " role="main" id="main_container" >
    <% if controller.controller_name == "help" %>
      <%= render 'layouts/help_sidebar' %>
    <% else %>
      <%= yield %>
    <% end %>
  </div>
</body>
</html>